### PR TITLE
Created a workspace, mermaid.js file rendeder, and an enhancements file

### PR DESCRIPTION
**Pull request by nadyka**

### CODE REVIEW

**Comment by OlenaTokova** [comment]
1

**Comment by OlenaTokova** [comment]
1

**Review by OlenaTokova — APPROVED** [review]

**Comment by nadyka** [comment]
Please accept the pull request.

**Review by OlenaTokova — APPROVED** [review]

**Comment by OlenaTokova** [comment]
1

**Comment by OlenaTokova** [comment]
1

**Pull request merged**
